name: boardlooker_mobile
description: Boardlooker mobile app
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  go_router: ^7.1.1
  bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.6.0
  injectable: ^2.1.2
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: ^9.1.2
  http: ^1.1.0
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  internet_connection_checker: ^1.0.0+1
  freezed_annotation: ^2.4.1
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.3
  path_provider: ^2.1.1
  disk_space_plus: ^0.2.3





  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  floor_generator: ^1.4.2
  build: ^2.4.0



flutter:


  uses-material-design: true
  assets:
    - .env





